language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - /^\d\.\d\.\d.*$/
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  skip_cleanup: true
- provider: script
  script: "./gradlew deploy"
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: eD7rsivVnY6nWWfTb2Al5Bwxfd70EkWrosv34rjZWJ+a2bGUahybGorUy9/FK1plVvGJAfpaJQL96Zvq6GyWV5Xet1KwZnELBUKhAlFCOHUXGyAPTw6+fxOBSNOliaWyHBMSyqN3lW2vULS3sHgkKqJwXED4oMGGB3HaL+OB72XdDpFdB8ZT3hSRmCE6BQGEuIobijmhXcjkT5iUOs0nMq+x0FSTCFEn77U40VuHSAY1/W0mmMfHqmQz/v7CJmoe7Q5Ff4g0ZfSOupAWPFwRvAa614cTIdnxWRJmnhPO0m9qCbjOFThbH0WJPNq+KPfYW3Bvg/esLPxVhp2mEpkURDoJAOQNIzJfknrz3f9rg/wK4yafs+H6YwqTg+jV2e2pHodbjrdlJ8VanHDkVVCJ9/1e6Qq9FqZR2OA5iJq7MyRAnYYRtVxTD7b6r3siffU30+M/vF4elJEQvBtUCJCKuo6dZGfWDYPxL0jaKOqzDi+J/jI/l1ZW9dRGWMQUPtybJsZ8lJ9IO/Q2qc7o71FNOQqMnXq/BBvwTR7wsAwCuYGrcxJIlkSSVoLdCGOI7vcnksdm90UDe0pBfcnEpNeTUCY+z1ZgXhh3rxkyS/7xES0bIKsxfAgfD732c/ZposVEPNRNTz1ZMTJDUnvuEu8WF+wDbtjnzoJwsOuKpv9ef1E=
  - secure: jJh3kqbwrzAZkd3DkU+YblBIMd9DQ89xOp2AMpimICsCtJ5l0mTZt9UquUlHofrvYM5tFtFfy7hiyZrYGf0TBoA8qL7Ze3YiVmT7rb2GBDPJ2UkSTQc7LQvvDZ903SQ7+T/O7zigqEupEMb3uAkCh6uYFfbNlLyZIEJwdYnbuoB2mkd24Vgfcm5m6dc3Swmact9n82LiOEBH2ymvZ9MNl70XmutGXfMd73lnlSBlcKH7z+LgKmlWCY/rEg72X0uTJ6AHhox87NGXC2eG1fyG5U/jp+IpqlJ03V5NVyqxW4+bRg/IRidH8IrID5eX6pa0Xu8NdmQ2/6Dd+IEINnkMCk8qQtWb2wYihkQZCiUpHkGRY9LSHFjAXL4gYKCPuGUhZQnpLFbMAMQZICpLeHjsMwOcyOcwM3g3LCct2uKgYFn7zX8K0EVN3UEzF2ax7Y7lOGtl5L+8xFFbx0A8LOR2Y0UBMGYk1ZDF4LkenzKufRio1Mk2GEZwrCeB9oYdilHc9/eMa1iVFYRCGBAZJXpQqXOjZmWbO4ca5e43Nwazp5KImoTpTd3+YahS1zLso47+RDPgUJfTTJARiSuMxGEEuXdOOaE5nYZfczTvcK+82d9//vjd/P7ZOjWcvTdyyKbDX1ysTIbt7481M2+2fP/O1zG7x6UojPA/OBIoYfQQw2s=
