# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: docker-compose-gradle-plugin
email: nico@nicolas-byl.eu
description: > # this means to ignore newlines until "baseurl:"
  Gradle plugin for docker-compose.
baseurl: "/docker-compose-gradle-plugin" # the subpath of your site, e.g. /blog
url: "http://nbyl.github.io/" # the base hostname & protocol for your site
twitter_username: NicolasByl
github_username:  nbyl

collections:
  guides:
    output: true
    permalink: /guides/:path/

# Build settings
markdown: kramdown
